services:
  cb-autodor-redis:
    image: redis:latest
    container_name: cb-autodor-redis
    hostname: cb-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - cb-autodor-redis-data:/data
    env_file:
      - .env
    networks:
      - cb-autodor-net

  cb-autodor-db:
    image: postgres:14-alpine
    container_name: cb-autodor-db
    command: [
      "postgres",
      "-c", "max_connections=200",
      "-c", "shared_buffers=2GB",
      "-c", "work_mem=32MB",
      "-c", "effective_cache_size=6GB"
    ]
    restart: always
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - cb-autodor-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - cb-autodor-net
    mem_limit: 8g
    logging:
      driver: "json-file"
      options:
        max-size: "20g"
        max-file: "1"


  cb-autodor-app:
    build:
      context: .
      dockerfile: _config/app/Dockerfile
    container_name: cb-autodor-app
    command: bash run.sh
    env_file:
      - .env
    environment:
      WAIT_HOSTS: cb-autodor-db:5432,cb-autodor-redis:6379
    volumes:
      - ./src:/app/marketplace
    ports:
      - "8000:8000"
      - "8001:8001"
    tty: true
    restart: on-failure
    depends_on:
      - cb-autodor-db
      - cb-autodor-redis
    networks:
      - cb-autodor-net
    logging:
      driver: "json-file"
      options:
        max-size: "20g"
        max-file: "1"

  cb-autodor-celery:
    build:
      context: .
      dockerfile: _config/app/Dockerfile
    container_name: cb-autodor-celery
    command: celery --app _project worker --beat -l info --concurrency=${CELERY_CONCURRENCY:-4}
    env_file:
      - .env
    environment:
      WAIT_HOSTS: cb-autodor-db:5432,cb-autodor-redis:6379
      CELERY_CONCURRENCY: 4
    volumes:
      - ./src:/app/marketplace
    restart: always
    depends_on:
      - cb-autodor-db
      - cb-autodor-redis
    networks:
      - cb-autodor-net

volumes:
  cb-autodor-db-data:
  cb-autodor-redis-data:

networks:
  cb-autodor-net:
    driver: bridge
