# Generated by Django 4.2.4 on 2025-11-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='employee',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет должности'), (1, 'Водитель'), (2, 'Менеджер'), (3, 'Посредник'), (4, 'Админ')], default=0, verbose_name='Тип пользователя'),
        ),
        migrations.AddField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 1'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 2'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_3',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 3'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_4',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 4'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_5',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 5'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_6',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 6'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_7',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 7'),
        ),
        migrations.AddField(
            model_name='settingsglobale',
            name='document_file_8',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='файл 8'),
        ),
        migrations.AlterField(
            model_name='contactpageinformation',
            name='page_type',
            field=models.CharField(choices=[('Карты', (('map_default', 'Карта по умолчанию'), ('map', 'Остальные карты'))), ('Электроная почта', (('email_default', 'Почта по умолчанию'), ('email', 'Остальные почты'))), ('Номера телефонов', (('phone_default', 'Номер телефона по умолчанию'), ('phone', 'Остальные номера телефонов'))), ('Адресса', (('address_default', 'Адресс по умолчанию'), ('address', 'Остальные адресса')))], max_length=50, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='MessagesChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmain.blogs')),
            ],
            options={
                'verbose_name': 'Комментарий тикета',
                'verbose_name_plural': 'Комментарии тикета',
            },
        ),
    ]
