# Generated by Django 4.2.4 on 2025-11-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_faqs_employee_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpageinformation',
            name='page_type',
            field=models.CharField(choices=[('Адресса', (('address_default', 'Адресс по умолчанию'), ('address', 'Остальные адресса'))), ('Электроная почта', (('email_default', 'Почта по умолчанию'), ('email', 'Остальные почты'))), ('Карты', (('map_default', 'Карта по умолчанию'), ('map', 'Остальные карты'))), ('Номера телефонов', (('phone_default', 'Номер телефона по умолчанию'), ('phone', 'Остальные номера телефонов')))], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='pagetype',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новости'), (2, 'Поиск'), (3, 'Контакты'), (4, 'ЧаВО'), (5, 'Авторизация'), (6, 'Регистрация'), (7, 'Сбросить пароль'), (8, 'Профиль'), (9, 'Сменить пароль'), (10, 'Паспортные данные'), (11, 'Уведомление')], default=1, verbose_name='Странца'),
        ),
    ]
