# Generated by Django 4.2.4 on 2025-11-23 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='марка')),
                ('model_auto', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='модель')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('original_link', models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Оригинальная ссылка')),
                ('price', models.IntegerField(db_index=True, verbose_name='Стоимость')),
                ('currency', models.CharField(db_index=True, max_length=10, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='Список ссылок на изображения')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('mileage', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Километраж (км)')),
                ('color', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Цвет')),
                ('doors', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Количество дверей')),
                ('power', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Мощность (л.с.)')),
                ('engine_volume', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=4, null=True, verbose_name='Объём двигателя (л)')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Год выпуска')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('image_no', models.BooleanField(db_index=True, default=True, verbose_name='Не имеет изображения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор'), ('robot', 'Робот')], db_index=True, max_length=20, null=True, verbose_name='Коробка передач')),
                ('fuel', models.CharField(blank=True, choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('gas', 'Газ / LPG / CNG')], db_index=True, max_length=20, null=True, verbose_name='Топливо')),
                ('drive', models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], db_index=True, max_length=10, null=True, verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AdvertAplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость')),
                ('delevery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость доставки')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='Номер заказа')),
                ('advert_id', models.CharField(db_index=True, max_length=20, verbose_name='ID объявления (во внешней БД)')),
                ('advert_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название объявления')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на объявление',
                'verbose_name_plural': 'Заявки на объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertAplicationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Фото или видео', upload_to='advert_gallery/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertAplicationGalleryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа медиа',
                'verbose_name_plural': 'Группы медиа',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert_applications/')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='advert_documents/', verbose_name='Файл документа')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Накладная'), ('contract', 'Договор'), ('customs', 'Таможенная')], max_length=20, verbose_name='Тип документа')),
                ('update_data', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Статья расходов')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Расход по заявке',
                'verbose_name_plural': 'Расходы по заявкам',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Advertpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='марка')),
                ('model_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='модель')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('original_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Оригинальная ссылка')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='Список ссылок на изображения')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Километраж (км)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество дверей')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Объём двигателя (л)')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор'), ('robot', 'Робот')], max_length=20, null=True, verbose_name='Коробка передач')),
                ('fuel', models.CharField(blank=True, choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('gas', 'Газ / LPG / CNG')], max_length=20, null=True, verbose_name='Топливо')),
                ('drive', models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=10, null=True, verbose_name='Привод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Купленное',
                'verbose_name_plural': 'Купленные',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('caller_offer', models.TextField(blank=True, null=True)),
                ('callee_answer', models.TextField(blank=True, null=True)),
                ('caller_ice_candidates', models.TextField(default='[]')),
                ('callee_ice_candidates', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название марки')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Легковая'), (2, 'Грузовая')], default=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CartVod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма к выплате водителю', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма выплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи о выплате', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время последнего обновления записи', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Выплата водителю',
                'verbose_name_plural': 'Выплаты водителям',
                'db_table': 'driver_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('status', models.SmallIntegerField(choices=[(0, 'Отправлено'), (1, 'Прочитано')], default=1, editable=False, verbose_name='Статус')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.TextField(verbose_name='Электронная почта')),
                ('subject', models.TextField(verbose_name='Обьект сотрудничества')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запрос на сотрудничество',
                'verbose_name_plural': 'Запросы на сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название статьи')),
            ],
            options={
                'verbose_name': 'Маска статьи расхода',
                'verbose_name_plural': 'Маски статей расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notificationgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('message', models.TextField()),
                ('slug', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'Груповое уведомление',
                'verbose_name_plural': 'Груповые уведомления',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('request', models.CharField(max_length=255, verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='PathResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Дополнение')),
            ],
        ),
        migrations.CreateModel(
            name='Stopwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Стоп слова')),
            ],
            options={
                'verbose_name': 'Стоп слово',
                'verbose_name_plural': 'Стоп слова',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Email')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Новое'), (1, 'Обратная связь'), (2, 'В процессе'), (3, 'Решенный'), (4, 'Закрытый')], default=0, verbose_name='Статус')),
                ('themas', models.TextField(verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Заказчик'), (1, 'Поддержка')], default=1, editable=False, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий тикета',
                'verbose_name_plural': 'Комментарии тикета',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket/%Y/%m/%d/tiket_file/')),
            ],
            options={
                'verbose_name': 'Файл комментария тикета',
                'verbose_name_plural': 'Файлы комментариев тикета',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('type', models.SmallIntegerField(choices=[(0, 'Пополнение'), (1, 'Списание')], default=0, verbose_name='Пополнение/Списание')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='moderation.advertaplication')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
    ]
