# Generated by Django 4.2.4 on 2025-11-23 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ticketcommentmedia',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='moderation.ticketcomment'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moderation.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='pathresponsibility',
            name='path_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.path', verbose_name='Путь выбор пути'),
        ),
        migrations.AddField(
            model_name='pathresponsibility',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='path',
            name='aplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='notificationgroups',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('blogs', 'pages', 'categorysblogs', 'tagsblogs')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificationgroups',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'employee': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='applications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessage', to='moderation.advertaplication', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='views',
            field=models.ManyToManyField(related_name='viewsmessage', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='cartvod',
            name='application',
            field=models.ForeignKey(help_text='Заявка, за которую производится выплата', on_delete=django.db.models.deletion.CASCADE, related_name='driver_payments', to='moderation.advertaplication', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='cartvod',
            name='voditel',
            field=models.ForeignKey(help_text='Водитель, выполняющий заявку', on_delete=django.db.models.deletion.CASCADE, related_name='driver_carts', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='moderation.carbrand', verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='callee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertpayment',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.carbrand'),
        ),
        migrations.AddField(
            model_name='advertpayment',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.carmodel'),
        ),
        migrations.AddField(
            model_name='advertexpense',
            name='aplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='moderation.advertaplication', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='advertdocument',
            name='aplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='moderation.advertaplication', verbose_name='заявка'),
        ),
        migrations.AddField(
            model_name='advertapplicationimage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallerygroup',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_groups', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallery',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallery',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Можно прикрепить к альбому', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='moderation.advertaplicationgallerygroup'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallery',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='advert_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='user_drivers',
            field=models.ManyToManyField(blank=True, related_name='advert_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Водители'),
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='user_menager',
            field=models.ManyToManyField(blank=True, related_name='advert_menager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
        migrations.AddField(
            model_name='advert',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='moderation.carbrand'),
        ),
        migrations.AddField(
            model_name='advert',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='moderation.carmodel'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['application', 'driver', '-timestamp'], name='moderation__applica_c54295_idx'),
        ),
        migrations.AddIndex(
            model_name='cartvod',
            index=models.Index(fields=['voditel', 'created_at'], name='driver_cart_voditel_b01932_idx'),
        ),
        migrations.AddIndex(
            model_name='cartvod',
            index=models.Index(fields=['application'], name='driver_cart_applica_d1f7b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartvod',
            unique_together={('voditel', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name')},
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['brand', 'model_auto'], name='moderation__brand_58d110_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['price', 'created_at'], name='moderation__price_b2ecea_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['year', 'created_at'], name='moderation__year_3bbab5_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['mileage', 'created_at'], name='moderation__mileage_7a43e1_idx'),
        ),
    ]
