# Generated by Django 4.2.4 on 2025-11-23 19:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertAplicationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Фото или видео', upload_to='advert_gallery/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertAplicationGalleryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа медиа',
                'verbose_name_plural': 'Группы медиа',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert_applications/')),
            ],
        ),
        migrations.CreateModel(
            name='Advertpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='марка')),
                ('model_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='модель')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('original_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Оригинальная ссылка')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='Список ссылок на изображения')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Километраж (км)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество дверей')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Объём двигателя (л)')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор'), ('robot', 'Робот')], max_length=20, null=True, verbose_name='Коробка передач')),
                ('fuel', models.CharField(blank=True, choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('gas', 'Газ / LPG / CNG')], max_length=20, null=True, verbose_name='Топливо')),
                ('drive', models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=10, null=True, verbose_name='Привод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Купленное',
                'verbose_name_plural': 'Купленные',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название марки')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Легковая'), (2, 'Грузовая')], default=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CartVod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма к выплате водителю', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма выплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи о выплате', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время последнего обновления записи', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Выплата водителю',
                'verbose_name_plural': 'Выплаты водителям',
                'db_table': 'driver_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название статьи')),
            ],
            options={
                'verbose_name': 'Маска статьи расхода',
                'verbose_name_plural': 'Маски статей расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('request', models.CharField(max_length=255, verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='PathResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Дополнение')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('type', models.SmallIntegerField(choices=[(0, 'Пополнение'), (1, 'Списание')], default=0, verbose_name='Пополнение/Списание')),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
        migrations.RemoveField(
            model_name='advertaplication',
            name='advert',
        ),
        migrations.RemoveField(
            model_name='advertdocument',
            name='advert',
        ),
        migrations.AddField(
            model_name='advert',
            name='image_no',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Не имеет изображения'),
        ),
        migrations.AddField(
            model_name='advert',
            name='published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='advert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='advert_id',
            field=models.CharField(db_index=True, default=1, max_length=20, verbose_name='ID объявления (во внешней БД)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='advert_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название объявления'),
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='delevery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='advertaplication',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='advertdocument',
            name='aplication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='moderation.advertaplication', verbose_name='заявка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertdocument',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertdocument',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertdocument',
            name='update_data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='марка'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='currency',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Количество дверей'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='drive',
            field=models.CharField(blank=True, choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], db_index=True, max_length=10, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='engine_volume',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=4, null=True, verbose_name='Объём двигателя (л)'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='fuel',
            field=models.CharField(blank=True, choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('gas', 'Газ / LPG / CNG')], db_index=True, max_length=20, null=True, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Километраж (км)'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='model_auto',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='original_link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='power',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(db_index=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор'), ('robot', 'Робот')], db_index=True, max_length=20, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='advertaplication',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='advertaplication',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='advert_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='advertaplication',
            name='user_drivers',
            field=models.ManyToManyField(blank=True, related_name='advert_drivers', to=settings.AUTH_USER_MODEL, verbose_name='Водители'),
        ),
        migrations.AlterField(
            model_name='advertaplication',
            name='user_menager',
            field=models.ManyToManyField(blank=True, related_name='advert_menager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['brand', 'model_auto'], name='moderation__brand_58d110_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['price', 'created_at'], name='moderation__price_b2ecea_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['year', 'created_at'], name='moderation__year_3bbab5_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['mileage', 'created_at'], name='moderation__mileage_7a43e1_idx'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='pathresponsibility',
            name='path_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.path', verbose_name='Путь выбор пути'),
        ),
        migrations.AddField(
            model_name='pathresponsibility',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='path',
            name='aplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'employee': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartvod',
            name='application',
            field=models.ForeignKey(help_text='Заявка, за которую производится выплата', on_delete=django.db.models.deletion.CASCADE, related_name='driver_payments', to='moderation.advertaplication', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='cartvod',
            name='voditel',
            field=models.ForeignKey(help_text='Водитель, выполняющий заявку', on_delete=django.db.models.deletion.CASCADE, related_name='driver_carts', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='moderation.carbrand', verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='advertpayment',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.carbrand'),
        ),
        migrations.AddField(
            model_name='advertpayment',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.carmodel'),
        ),
        migrations.AddField(
            model_name='advertapplicationimage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallerygroup',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_groups', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallery',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='moderation.advertaplication'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallery',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Можно прикрепить к альбому', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='moderation.advertaplicationgallerygroup'),
        ),
        migrations.AddField(
            model_name='advertaplicationgallery',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advert',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='moderation.carbrand'),
        ),
        migrations.AddField(
            model_name='advert',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='moderation.carmodel'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['application', 'driver', '-timestamp'], name='moderation__applica_c54295_idx'),
        ),
        migrations.AddIndex(
            model_name='cartvod',
            index=models.Index(fields=['voditel', 'created_at'], name='driver_cart_voditel_b01932_idx'),
        ),
        migrations.AddIndex(
            model_name='cartvod',
            index=models.Index(fields=['application'], name='driver_cart_applica_d1f7b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartvod',
            unique_together={('voditel', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name')},
        ),
    ]
