# Generated by Django 4.2.4 on 2025-11-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('uploaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Прослушка',
                'verbose_name_plural': 'Прослушки',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='device_token',
            field=models.TextField(blank=True, null=True, verbose_name='FCM токен устройства'),
        ),
        migrations.AddField(
            model_name='profile',
            name='listen',
            field=models.BooleanField(default=False, verbose_name='Слушать'),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_hands',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет должности'), (1, 'Водитель'), (2, 'Менеджер'), (3, 'Посредник'), (4, 'Админ')], default=0, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Сотрудники'), (1, 'Клиент')], default=1, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
